Stacking internal evaluation
JuliaAI/MLJBase.jl pull request #712
Opened 2022-01-06 18:38 UTC by olivierlabayle

I have played around with the stack again. Related to the new functionality [permitting to expose the internal state of a learning network](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Exposing-internal-state-of-a-learning-network) that you offered in 0.19. The goal would be to optionally report the internal cross validation result of the stack for a given set of measures.

Even though not complete, I think the following provides a poc for this. Before moving forward I wanted to see if you could give me some feedback and guidance on where to go next. A few ideas that come to my mind:

- Formatting of the report, maybe something matching the output of `evaluate!`?
- Maybe I should check that the measures match the stack type?

I hope you can find some time to look into it and happy to take feedback.

2022-01-06 20:50 UTC, ablaom commented
Thanks for this further contribution!
 
Will take a look in due course. In the meantime, could you clarify if this is just adding features, or is it also breaking?

2022-01-06 22:53 UTC, olivierlabayle commented
No it shouldn't be breaking at all. It should be transparent to the user if using the general `Stack` constructor as it's only a new keyword argument that defaults to no evaluation.

2022-01-10 00:11 UTC, ablaom commented
This is a very cool application of the new interface. I'd be kind of surprised if any other stacking software exposes the kind of detail this PR adds. Nice work!

The POC looks good to me and I'd support it more-or-less as is, notwithstanding the two items you already mention.

I do see one wrinkle.  Base learners can be a mixture of probabilistic and deterministic models, yes? So, am I allowed to include a probabilistic measure? If so, I guess it needs to be ignored by the deterministic models. Or do we just rule out probabilistic measures altogether to rule out the added complexity. Probably. 

For the record, `evaluate!` allows the user to specify both kinds of measures if the model is probabilisitic. It also allows you to pass weights to the measures. Maybe you can make call some of that code to handle these kind of case distinctions, add some functionality, and to check the validity of the measures. Can provide further guidance on that code if necessary.

2022-01-23 17:55 UTC, olivierlabayle commented
@ablaom Thank you for your patience and sorry for the delay, I think this is now ready for review.

A few notes:

- I finally chose the `PerformanceEvaluation` type return for each model which makes this PR a bit more involved. The implementation is tested by comparing the result with an actual call to `evaluate` with the same strategy.

- I am not sure I have addressed the probabilistic measure issue you mention. I think it should work for a ProbabilisticStack since it currently can only combine probabilistic learners if I recall. For a DeterministicStack it may not as you mention. However I have made use of `_actual_operations` which should select the appropriate operation for the measure. It seems to boil down to weither a model implements the required operation. Do you have any testcase that I could use? I am happy to take your guidance on this, I could probably add a `_cheack_measures` call at the begining of the `fit` to fail fast if you think it is relevant. The problem being that `_cheack_measures` requires `y` and cannot be called at construction time.

- Finally there is no support for weights.

2022-01-23 20:52 UTC, ablaom commented on src/composition/models/stacking.jl
>      metalearner === nothing &&
Minor suggestion. We could allow the user to specify *singular* `measure=...` by instead doing

```julia
function Stack(;metalearner=nothing, resampling=CV(), resapling=CV(), measure=nothing, measures=measure, named_models...)
```
with no need to change anything downstream.

2022-01-23 22:18 UTC, ablaom commented on src/composition/models/stacking.jl
> +
I'm struggling a bit to understand what the role of each `internal_stack_report` is doing. There is one on 279, 282, and 286. I think a few code comments here might help me. 

I'm also struggling to find where the `fold_evaluations` are transformed from a list of `Nodes` to a list of "concrete" tuples. That is, where does the actual evaluation happen?

2022-01-23 22:22 UTC, ablaom commented
> @ablaom Thank you for your patience and sorry for the delay, I think this is now ready for review.
> 
> A few notes:
> 
> * I finally chose the `PerformanceEvaluation` type return for each model which makes this PR a bit more involved. The implementation is tested by comparing the result with an actual call to `evaluate` with the same strategy.

Awesome!

> * I am not sure I have addressed the probabilistic measure issue you mention. I think it should work for a ProbabilisticStack since it currently can only combine probabilistic learners if I recall. For a DeterministicStack it may not as you mention. However I have made use of `_actual_operations` which should select the appropriate operation for the measure. It seems to boil down to weither a model implements the required operation. Do you have any testcase that I could use? 

Looking over your tests, I think you have addressed my original issue. 

> I am happy to take your guidance on this, I could probably add a `_cheack_measures` call at the begining of the `fit` to fail fast if you think it is relevant. The problem being that `_cheack_measures` requires `y` and cannot be called at construction time.

I think such a check would probably be a good idea.

> * Finally there is no support for weights.

Could always be added later. This PR already exceeds my expectations.

2022-01-24 00:23 UTC, ablaom requested changes
@olivierlabayle Thanks for going the extra mile here to recover the full `PerformanceEvaluation` objects. 

Your tests look pretty comprehensive to me and I'm happy with what codecov is reporting.

2022-01-24 09:03 UTC, olivierlabayle commented on src/composition/models/stacking.jl
> +
I added some doctrings and hope this is now easier to understand.

2022-01-24 09:30 UTC, olivierlabayle commented
As discussed, I found a usecase and added `check_stack_measures` call at the beginning of `fit`. I also updated the `setproperty!` method to encompass the `measures` field which was missing.

2022-01-25 02:16 UTC, ablaom approved these changes
All looks good to me. Thanks!

2022-01-25 02:16 UTC, merged